### ISSUE TITLE
Can we have a t-prefix similar to `bool` which would also define `\footrue` and `\foofalse`?

### ISSUE THREAD

**Issue by niruvt** [Skillmon/tex_expkv#3]
As I understand it, `bool` and friends don't define `\footrue` and `\foofalse` and users have to define them on their own. From my experience I need them often, so I wanted to know if we can have a t-prefix which provides them. Because right now at least one probable redundancy that I can think of is `bool foo \iffoo` will set `\iffoo` and if I need `\footrue`, `\foofalse` I will have to use `\newif\iffoo` which will once again set `\iffoo`. So if `expkv` itself provides a new t-prefix which will set `\footrue` and `\foofalse` it would be great IMO.

**Comment by Skillmon** [comment]
You could do

```
\newif\iffoo
\ekvdefinekeys{example}{bool foo = \iffoo}
```

and `expkv-def` wouldn't redefine `\iffoo`. The only case in which `\iffoo` will be defined is if it's undefined when the `bool`-type is processed.

**Comment by niruvt** [comment]
IMO this is a not-so-obvious dependency at least for TeX-coders, because the popular TeX-boolean does define `\footrue` and `\foofalse` too. It looks unusual because of the habit. Though you have documented it, probably it's not something that would quickly come to one's mind, e.g., consider the code provided in [this](https://github.com/Skillmon/tex_expkv/issues/2#issuecomment-1288132908) comment. `\ekvdefinekeys` would look exactly the same even in the case where `\footrue` and `\foofalse` were available with a prior `\newif\iffoo`. I think two distinct behaviors should be distinguished by two distinct function-variables too. If someone uses `newiflikebool foo = \iffoo` explicitly, when they want `\footrue`, `\foofalse` their code will automatically become more productive, since this chunk can be reused without looking at the prior settings and still produce the same results. Also with the current settings people would be expected to strictly use `\newif\iffoo` prior to `bool foo = \iffoo`. Adding it after would become redundant (or will it just fail? I am not sure and haven't checked). Hence this new t-prefix would benefit some users who want their code to be simpler and more independent.

(Not a bug, just a feature-request maybe.)

**Comment by Skillmon** [comment]
Well, a later `\newif` will just do the same as an earlier `\newif`, and the order doesn't matter much. The reason behind that behaviour of the `bool` key is because it shares its inner workings with the `boolTF` and the `invbool` key types, and honestly, I don't see that much advantage of providing another key type with the sole difference being the initialisation done via `\newif` when this just requires one additional line of code if it is really needed (also: compare with the `pgfkeys` which provides the `.is if` handler that doesn't do any initialisation, so always requires the user to do the `\newif` part -- that's not meant as a "other packages don't so I won't because of that", after all there are deliberate differences in `expkv` compared to many if not all other key=val interfaces for a reason).

To conclude: I'm pretty reluctant to adding this, and I won't change the behaviour of the existing key types to do this.
